services:
  miki-bot:
    build: .
    container_name: miki_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./src/database:/app/src/database  # Persistencia para tu SQLite